// SPDX-FileCopyrightText: 2026 Lusoris <lusoris@proton.me>
// SPDX-License-Identifier: EUPL-1.2

//! The bounded, allocation-free identifiers P13 carries.
//!
//! `docs/integration/stack.md` asks every crossing to carry a correlation
//! identifier; the P16-to-P13 query also names the candidate it is about, and
//! the P13-to-P07 shift names the cgroup slice it defers. All three are
//! validated on construction and stored inline, so no decision path allocates
//! for one and none can be silently truncated or sanitised: a malformed input
//! is refused.
//!
//! The three types are written out rather than generated by a macro. The
//! public-surface sweep in `tests/public_surface.rs` reads declarations as
//! text, so a macro-generated `pub struct` would be surface the sweep cannot
//! see -- which is the shape of hole the M15 verification found.

use core::fmt;

use crate::error::TellusError;

/// Scalar upper bound, in bytes, on any P13 identifier.
pub const MAX_IDENTIFIER_LEN: usize = 64;

/// Returns `true` for the bytes permitted inside a P13 identifier.
const fn permitted(byte: u8) -> bool {
    byte.is_ascii_alphanumeric() || matches!(byte, b'.' | b'-' | b'_' | b':' | b'@' | b'/')
}

/// Validates `raw` and copies it into a fixed inline buffer.
///
/// `label` is the refusal text, so each identifier says which kind it is
/// without the caller having to match on a type.
fn parse_into(
    raw: &str,
    label: &'static str,
) -> Result<([u8; MAX_IDENTIFIER_LEN], u8), TellusError> {
    let source = raw.as_bytes();
    if source.is_empty() || source.len() > MAX_IDENTIFIER_LEN {
        return Err(TellusError::Identifier { reason: label });
    }
    let len = u8::try_from(source.len()).map_err(|_| TellusError::Identifier { reason: label })?;
    let mut bytes = [0u8; MAX_IDENTIFIER_LEN];
    for (slot, byte) in bytes.iter_mut().zip(source.iter()) {
        if !permitted(*byte) {
            return Err(TellusError::Identifier { reason: label });
        }
        *slot = *byte;
    }
    Ok((bytes, len))
}

/// A validated correlation identifier of at most [`MAX_IDENTIFIER_LEN`] bytes.
///
/// It threads a query to the response it produced, so a refusal names the
/// conversation it belonged to without echoing the payload into a log.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct CorrelationId {
    bytes: [u8; MAX_IDENTIFIER_LEN],
    len: u8,
}

impl CorrelationId {
    /// The refusal text this identifier reports.
    pub const REFUSAL: &'static str =
        "a correlation identifier is empty, over-long, or outside the permitted character set";

    /// Parses `raw` into a correlation identifier.
    ///
    /// # Errors
    ///
    /// Returns [`TellusError::Identifier`] when `raw` is empty, longer than
    /// [`MAX_IDENTIFIER_LEN`] bytes, or carries a byte outside the permitted
    /// character set. The input is never truncated or sanitised.
    pub fn parse(raw: &str) -> Result<Self, TellusError> {
        let (bytes, len) = parse_into(raw, Self::REFUSAL)?;
        Ok(Self { bytes, len })
    }

    /// Returns the validated bytes, without the trailing padding.
    #[must_use]
    pub fn as_bytes(&self) -> &[u8] {
        self.bytes.get(..usize::from(self.len)).unwrap_or(&[])
    }

    /// Returns the length in bytes.
    #[must_use]
    pub const fn len(&self) -> usize {
        self.len as usize
    }

    /// Returns `false`; a correlation identifier is never empty by construction.
    #[must_use]
    pub const fn is_empty(&self) -> bool {
        self.len == 0
    }
}

impl fmt::Display for CorrelationId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let text = core::str::from_utf8(self.as_bytes()).map_err(|_| fmt::Error)?;
        f.write_str(text)
    }
}

/// A validated candidate identifier of at most [`MAX_IDENTIFIER_LEN`] bytes.
///
/// The imported P16 scaffold (export-025 `6b23723ddb76`) guards the empty
/// identifier with `assert!(!candidate_id.is_empty())`, which aborts the
/// process. Here the empty identifier simply does not become a value, which is
/// what HISS-07 asks for and what makes the negative case an ordinary test.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct CandidateId {
    bytes: [u8; MAX_IDENTIFIER_LEN],
    len: u8,
}

impl CandidateId {
    /// The refusal text this identifier reports.
    pub const REFUSAL: &'static str =
        "a candidate identifier is empty, over-long, or outside the permitted character set";

    /// Parses `raw` into a candidate identifier.
    ///
    /// # Errors
    ///
    /// Returns [`TellusError::Identifier`] when `raw` is empty, longer than
    /// [`MAX_IDENTIFIER_LEN`] bytes, or carries a byte outside the permitted
    /// character set. The input is never truncated or sanitised.
    pub fn parse(raw: &str) -> Result<Self, TellusError> {
        let (bytes, len) = parse_into(raw, Self::REFUSAL)?;
        Ok(Self { bytes, len })
    }

    /// Returns the validated bytes, without the trailing padding.
    #[must_use]
    pub fn as_bytes(&self) -> &[u8] {
        self.bytes.get(..usize::from(self.len)).unwrap_or(&[])
    }

    /// Returns the length in bytes.
    #[must_use]
    pub const fn len(&self) -> usize {
        self.len as usize
    }

    /// Returns `false`; a candidate identifier is never empty by construction.
    #[must_use]
    pub const fn is_empty(&self) -> bool {
        self.len == 0
    }
}

impl fmt::Display for CandidateId {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let text = core::str::from_utf8(self.as_bytes()).map_err(|_| fmt::Error)?;
        f.write_str(text)
    }
}

/// A validated cgroup v2 slice name of at most [`MAX_IDENTIFIER_LEN`] bytes.
///
/// It is a name, not a handle: nothing in this crate opens a cgroup, reads one,
/// or asks the kernel whether it exists.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct SliceName {
    bytes: [u8; MAX_IDENTIFIER_LEN],
    len: u8,
}

impl SliceName {
    /// The refusal text this identifier reports.
    pub const REFUSAL: &'static str =
        "a cgroup slice name is empty, over-long, or outside the permitted character set";

    /// Parses `raw` into a cgroup slice name.
    ///
    /// # Errors
    ///
    /// Returns [`TellusError::Identifier`] when `raw` is empty, longer than
    /// [`MAX_IDENTIFIER_LEN`] bytes, or carries a byte outside the permitted
    /// character set. The input is never truncated or sanitised.
    pub fn parse(raw: &str) -> Result<Self, TellusError> {
        let (bytes, len) = parse_into(raw, Self::REFUSAL)?;
        Ok(Self { bytes, len })
    }

    /// Returns the validated bytes, without the trailing padding.
    #[must_use]
    pub fn as_bytes(&self) -> &[u8] {
        self.bytes.get(..usize::from(self.len)).unwrap_or(&[])
    }

    /// Returns the length in bytes.
    #[must_use]
    pub const fn len(&self) -> usize {
        self.len as usize
    }

    /// Returns `false`; a cgroup slice name is never empty by construction.
    #[must_use]
    pub const fn is_empty(&self) -> bool {
        self.len == 0
    }
}

impl fmt::Display for SliceName {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let text = core::str::from_utf8(self.as_bytes()).map_err(|_| fmt::Error)?;
        f.write_str(text)
    }
}
